# GET http://localhost:4000/formData/states


POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "Arjj@dfghj.com",
  "phoneNumber": "3456789"
}

###

POST http://localhost:4000/user/update
Content-Type: application/json

{
  "email": "hari",
  "phoneNumber": "9500",
  "donate" : true
}